### ISSUE TITLE
Weather page of dash shows incorrect temperature(s)

### ISSUE THREAD

**Issue by dtredger** [switchdoclabs/SDL_Pi_WeatherSense#1]
The temperature numbers on the _Weather_ tab of the dash do not change when `English_Metric = 1` in _config.py_ is changed, even though the Displayed _units_ (°C and °F) do change. It appears the outside Sensor (FT020TAIO) always displays Fahrenheit, and the inside sensor always Celsius.

In [line 111 of SDL_Pi_WeatherSense.py](https://github.com/switchdoclabs/SDL_Pi_WeatherSense/blob/ea7fb344657c4d99ceafc9091b674f2a2c7125f4/wirelessSensors.py#L111) the temp is read and converted to Fahrenheit, and that's what is stored in the DB:
```python 
wTemp = (wTemp - 400) / 10.0
```

In _SDL_Pi_WeatherSense.py_, the **OutdoorTemperature** and **IndoorTemperature** seem to be processed in opposite ways:

[SDL_Pi_WeatherSense.py - Line 127](https://github.com/switchdoclabs/SDL_Pi_WeatherSense/blob/ea7fb344657c4d99ceafc9091b674f2a2c7125f4/wirelessSensors.py#L127)
```python
# convert temperature reading to Celsius but why?    
# OutdoorTemperature = round(((wTemp - 32.0) / (9.0 / 5.0)), 2)    
OutdoorTemperature = round(wTemp, 2)
```

[SDL_Pi_WeatherSense.py - Line 236](https://github.com/switchdoclabs/SDL_Pi_WeatherSense/blob/ea7fb344657c4d99ceafc9091b674f2a2c7125f4/wirelessSensors.py#L236)
```python
IndoorTemperature = round(((var["temperature_F"] - 32.0) / (9.0 / 5.0)), 2)    
#IndoorTemperature = var["temperature_F"]
```

The dash problem seems to be that, when the temperature is read from the DB in **dash_app/weather_page.py**, the _CTUnits_ function either converts the temp to Fahrenheit, or leaves as-is if the config is set to metric—but the default stored in the db for OutdoorTemperature is actually Fahrenheit.

[dash_app/weather_page.py#L92](https://github.com/switchdoclabs/SDL_Pi_WeatherSense/blob/ea7fb344657c4d99ceafc9091b674f2a2c7125f4/dash_app/weather_page.py#L92)
```python
def CTUnits(temperature):    
    English_Metric = config.English_Metric

    if English_Metric:  # english units 
        temperature = (9.0 / 5.0 * temperature) + 32.0
    return temperature
```

Also, it's a bit confusing to call the config setting _english_metric_ in this case, since England uses celsius...

**Comment by switchdoclabs** [comment]
Fixed in Version 004.
